In [1]:
# Structured Data: NumPy's Structured Arrays

In [2]:
import numpy as np

In [3]:
name = ['Alice', 'Bob', 'Cathy', 'Doug']
age = [25, 45, 37, 19]
weight = [55.0, 85.5, 68.0, 61.5]

In [4]:
x = np.zeros(4, dtype=int)

In [5]:
# Use a compound data type for structured arrays
data = np.zeros(4, dtype={'names':('name', 'age', 'weight'),
                          'formats':('U10', 'i4', 'f8')})
print(data.dtype)

[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')]


In [6]:
data['name'] = name
data['age'] = age
data['weight'] = weight
print(data)

[('Alice', 25, 55. ) ('Bob', 45, 85.5) ('Cathy', 37, 68. )
 ('Doug', 19, 61.5)]


In [7]:
# Get all names
data['name']

array(['Alice', 'Bob', 'Cathy', 'Doug'], dtype='<U10')

In [8]:
# Get first row of data
data[0]

('Alice', 25, 55.)

In [9]:
# Get the name from the last row
data[-1]['name']

'Doug'

In [10]:
# Get names where age is under 30
data[data['age'] < 30]['name']

array(['Alice', 'Doug'], dtype='<U10')

## Creating Structured Arrays

In [11]:
np.dtype({'names':('name', 'age', 'weight'),
          'formats':('U10', 'i4', 'f8')})

dtype([('name', '<U10'), ('age', '<i4'), ('weight', '<f8')])

In [12]:
np.dtype({'names':('name', 'age', 'weight'),
          'formats':((np.str_, 10), int, np.float32)})

dtype([('name', '<U10'), ('age', '<i4'), ('weight', '<f4')])

In [13]:
np.dtype([('name', 'S10'), ('age', 'i4'), ('weight', 'f8')])

dtype([('name', 'S10'), ('age', '<i4'), ('weight', '<f8')])

In [14]:
np.dtype('S10,i4,f8')

dtype([('f0', 'S10'), ('f1', '<i4'), ('f2', '<f8')])


|Character  |Description	        |Example  |
|:---------:|:---------------------:|:--------|
|'b'        |Byte	                |np.dtype('b')
|'i'	    |Signed integer	        |np.dtype('i4') == np.int32
|'u'	    |Unsigned integer	    |np.dtype('u1') == np.uint8
|'f'	    |Floating point	        |np.dtype('f8') == np.int64
|'c'	    |Complex floating point	|np.dtype('c16') == np.complex128
|'S', 'a'   |String	                |np.dtype('S5')
|'U'	    |Unicode string	        |np.dtype('U') == np.str_
|'V'	    |Raw data (void)	    |np.dtype('V') == np.void

## More Advanced Compound Types

In [15]:
tp = np.dtype([('id', 'i8'), ('mat', 'f8', (3, 3))])
X = np.zeros(1, dtype=tp)
print(X[0])
print(X['mat'][0])

(0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


## RecordArrays: Structured Arrays with a Twist 

In [16]:
data['age']

array([25, 45, 37, 19])

In [17]:
data_rec = data.view(np.recarray)
data_rec.age

array([25, 45, 37, 19])

In [18]:
%timeit data['age']
%timeit data_rec['age']
%timeit data_rec.age

74.9 ns ± 3.69 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)
1.04 µs ± 77.5 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
2.05 µs ± 145 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
