In [1]:
import numpy as np

# Introducing Broadcasting

In [2]:
a = np.array([0, 1, 2])
b = np.array([5, 5, 5])
a + b

array([5, 6, 7])

In [3]:
a + 5

array([5, 6, 7])

In [4]:
M = np.ones((3, 3))
M

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [5]:
M + a

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [6]:
a = np.arange(3)
b = np.arange(3)[:, np.newaxis]

print(a)
print(b)

[0 1 2]
[[0]
 [1]
 [2]]


In [7]:
a + b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

# Rules of Broadcasting

Rule 1: If the two arrays differ in their number of dimensions, the shape of the one with fewer dimensions is padded with ones on its leading (left) side.
<br>
Rule 2: If the shape of the two arrays does not match in any dimension, the array with shape equal to 1 in that dimension is stretched to match the other shape.
<br>
Rule 3: If in any dimension the sizes disagree and neither is equal to 1, an error is raised.

## Broadcasting example 1

In [8]:
M = np.ones((2, 3))
a = np.arange(3)

In [9]:
M + a

array([[1., 2., 3.],
       [1., 2., 3.]])

## Broadcasting example 2

In [10]:
a = np.arange(3).reshape((3, 1))
b = np.arange(3)

In [11]:
a + b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

## Broadcasting example 3

In [12]:
M = np.ones((3, 2))
a = np.arange(3)

In [13]:
M + a

ValueError: operands could not be broadcast together with shapes (3,2) (3,) 

In [ ]:
a[:, np.newaxis].shape

In [ ]:
M + a[:, np.newaxis]

In [ ]:
np.logaddexp(M, a[:, np.newaxis])

# Broadcasting in Practice

## Centering an array

In [ ]:
X = np.random.random((10, 3))

In [ ]:
Xmean = X.mean(0)
Xmean

In [ ]:
X_centered = X - Xmean

In [ ]:
X_centered.mean(0)

## Plotting a two-dimensional function

In [ ]:
# x and y have 50 steps from 0 to 5
x = np.linspace(0, 5, 50)
y = np.linspace(0, 5, 50)[:, np.newaxis]

z = np.sin(x) ** 10 + np.cos(10 + y * x) * np.cos(x)

In [ ]:
%matplotlib inline
import matplotlib.pyplot as plt

In [ ]:

plt.imshow(z, origin='lower', extent=[0, 5, 0, 5],
           cmap='viridis')
plt.colorbar();