In [97]:
import numpy as np


# NumPy Array Attributes

In [98]:
np.random.seed(0)  # seed for reproducibility



In [99]:
x1 = np.random.randint(10, size=3, dtype='int64')  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4), dtype='int64')  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5), dtype='int64')  # Three-dimensional array

In [100]:
print("x1 ndim: ", x1.ndim)
print("x1 shape:", x1.shape)
print("x1 size: ", x1.size)
print("x1 dtype:", x1.dtype)
print("x1 itemsize:", x1.itemsize, "bytes")
print("x1 nbytes:", x1.nbytes, "bytes")

x1 ndim:  1
x1 shape: (3,)
x1 size:  3
x1 dtype: int64
x1 itemsize: 8 bytes
x1 nbytes: 24 bytes


In [101]:
print("x2 ndim: ", x2.ndim)
print("x2 shape:", x2.shape)
print("x2 size: ", x2.size)
print("x2 dtype:", x2.dtype)
print("x2 itemsize:", x2.itemsize, "bytes")
print("x2 nbytes:", x2.nbytes, "bytes")

x2 ndim:  2
x2 shape: (3, 4)
x2 size:  12
x2 dtype: int64
x2 itemsize: 8 bytes
x2 nbytes: 96 bytes


In [102]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)
print("x3 dtype:", x3.dtype)
print("x3 itemsize:", x3.itemsize, "bytes")
print("x3 nbytes:", x3.nbytes, "bytes")

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60
x3 dtype: int64
x3 itemsize: 8 bytes
x3 nbytes: 480 bytes


# Array Indexing: Accessing Single Elements

In [103]:
x1

array([5, 0, 3], dtype=int64)

In [104]:
x1[0]

5

In [105]:
x1[2]

3

In [106]:
x1[-1]

3

In [107]:
x1[-2]

0

In [108]:
x2

array([[3, 7, 9, 3],
       [5, 2, 4, 7],
       [6, 8, 8, 1]], dtype=int64)

In [109]:
x2[0, 0]

3

In [110]:
x2[-1, -1]

1

In [111]:
x2[0, 0] = 12
x2

array([[12,  7,  9,  3],
       [ 5,  2,  4,  7],
       [ 6,  8,  8,  1]], dtype=int64)

In [112]:
# If you attempt to insert a floating-point value to an integer array, the value will be silently truncated
x2[1, 0] = 9.35
x2

array([[12,  7,  9,  3],
       [ 9,  2,  4,  7],
       [ 6,  8,  8,  1]], dtype=int64)

# Array Slicing: Accessing Subarrays

To access a slice of an array x:
<br>
x[start : stop : step]

## One-dimensional subarrays

In [113]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [114]:
x[:5]  # first five elements

array([0, 1, 2, 3, 4])

In [115]:
x[5:]  # elements after index 5

array([5, 6, 7, 8, 9])

In [116]:
x[4:7]  # middle sub-array

array([4, 5, 6])

In [117]:
x[::2]  # every other element

array([0, 2, 4, 6, 8])

In [118]:
x[1::2]  # every other element, starting at index 1

array([1, 3, 5, 7, 9])

A potentially confusing case is when the step value is negative. In this case, the defaults for start and stop are swapped.
<br>
x[start : stop : negative_step]

In [119]:
x[::-1]  # all elements, reversed

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [120]:
x[5:2:-1] 


array([5, 4, 3])

In [121]:
x[2:5:-1] 


array([], dtype=int32)

In [122]:
x[5::-2]  # reversed every other from index 5

array([5, 3, 1])

## Multi-dimensional subarrays

In [123]:
x2

array([[12,  7,  9,  3],
       [ 9,  2,  4,  7],
       [ 6,  8,  8,  1]], dtype=int64)

In [124]:
x2[:2, :3]  # two rows, three columns

array([[12,  7,  9],
       [ 9,  2,  4]], dtype=int64)

In [125]:
x2[:3, ::2]  # all rows, every other column

array([[12,  9],
       [ 9,  4],
       [ 6,  8]], dtype=int64)

In [126]:
x2[::-1, ::-1]

array([[ 1,  8,  8,  6],
       [ 7,  4,  2,  9],
       [ 3,  9,  7, 12]], dtype=int64)

### Accessing array rows and columns

In [127]:
print(x2[:, 0])  # first column of x2

[12  9  6]


In [128]:
print(x2[0, :])  # first row of x2

[12  7  9  3]


In [129]:
print(x2[0])  # equivalent to x2[0, :]

[12  7  9  3]


## Subarrays as no-copy views

In [130]:
print(x2)

[[12  7  9  3]
 [ 9  2  4  7]
 [ 6  8  8  1]]


In [131]:
x2_sub = x2[:2, :2]
print(x2_sub)

[[12  7]
 [ 9  2]]


In [132]:
#Iif we modify this subarray, the original array is changed
x2_sub[0, 0] = 99
print(x2_sub)

[[99  7]
 [ 9  2]]


In [133]:
print(x2)

[[99  7  9  3]
 [ 9  2  4  7]
 [ 6  8  8  1]]


## Creating copies of arrays

In [134]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[99  7]
 [ 9  2]]


In [135]:
x2_sub_copy[0, 0] = 42
print(x2_sub_copy)

[[42  7]
 [ 9  2]]


In [136]:
print(x2)

[[99  7  9  3]
 [ 9  2  4  7]
 [ 6  8  8  1]]


# Reshaping of Arrays

In [137]:
grid = np.arange(1, 10).reshape((3, 3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [138]:
x = np.array([1, 2, 3])

# row vector via reshape
x.reshape((1, 3))

array([[1, 2, 3]])

In [139]:
# row vector via newaxis
x[np.newaxis, :]

array([[1, 2, 3]])

In [140]:
# column vector via reshape
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [141]:
# column vector via newaxis
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

# Array Concatenation and Splitting

## Concatenation of arrays

```np.concatenate``` 
<br>
```np.vstack``` will vertically stack the arrays
<br>
```np.hstack``` will horizontally stack the arrays
<br>
```np.dstack``` will stack arrays along the third axis

In [142]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [143]:
z = [99, 99, 99]
print(np.concatenate([x, y, z]))

[ 1  2  3  3  2  1 99 99 99]


In [144]:
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])

In [145]:
# concatenate along the first axis
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [146]:
# concatenate along the second axis (zero-indexed)
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [148]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])

# vertically stack the arrays
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [147]:
# horizontally stack the arrays
y = np.array([[99],
              [99]])
np.hstack([grid, y])

array([[ 1,  2,  3, 99],
       [ 4,  5,  6, 99]])

## Splitting of arrays

```np.split``` 
<br>
```np.vsplit``` will vertically split the arrays
<br>
```np.hsplit``` will horizontally split the arrays
<br>
```np.dsplit ``` will split arrays along the third axis

In [154]:
x = [1, 2, 3, 99, 99, 3, 2, 1, 0]
x1, x2, x3 = np.split(x, [3, 5]) # x1 receives index 0 to 2, x2 receives index 3 to 4 and receives index 5 to the end of the array
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1 0]


In [155]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [160]:
upper, mid, lower = np.vsplit(grid, [2,3])
print(upper)
print(mid)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]]
[[12 13 14 15]]


In [161]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
