In [1]:
import array
import numpy as np

# Fixed-Type Arrays in Python

In [2]:
L = list(range(10))
A = array.array('i', L) # 'i' is a type code indicating the contents are integers.
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
L = ['a', 'b', 'c', 'd']
A = array.array('u', L) # 'u' is a type code indicating the contents are unicode.
type(A[1])

str

# Creating Arrays from Python Lists

In [4]:
# integer array:
np.array([1, 4, 2, 5, 3]) # Unlike Python lists, NumPy is constrained to arrays that all contain the same type

array([1, 4, 2, 5, 3])

In [5]:
np.array([3.14, 4, 2, 3]) # If types do not match, NumPy will upcast if possible

array([3.14, 4.  , 2.  , 3.  ])

In [6]:
np.array([3.14, 4, 2, 3, 'a', 'b']) # If types do not match, NumPy will upcast if possible

array(['3.14', '4', '2', '3', 'a', 'b'], dtype='<U32')

In [7]:
np.array([list(range(10)), list(range(10))]) # If types do not match, NumPy will upcast if possible


array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [8]:
np.array([1, 2, 3, 4], dtype='float32') # Explicit set the data type of the resulting array

array([1., 2., 3., 4.], dtype=float32)

In [9]:
# nested lists result in multi-dimensional arrays
np.array([range(i, i + 3) for i in [2, 4, 6]]) #  Unlike Python lists, NumPy arrays can explicitly be multi-dimensional

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

# Creating Arrays from Scratch

In [10]:
# Create a length-10 integer array filled with zeros
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [11]:
# Create a length-10 float array filled with zeros
np.zeros(10, dtype=float)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
# Create a length-10 list array filled with zeros
np.zeros(10, dtype=list)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=object)

In [13]:
# Create a length-10 string array filled with zeros
np.zeros(10, dtype=str)

array(['', '', '', '', '', '', '', '', '', ''], dtype='<U1')

In [14]:
# Create a 3x5 floating-point array filled with ones
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [15]:
# Create a 3x5 array filled with 3.14
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [16]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
# (this is similar to the built-in range() function)
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [17]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [18]:
# Create an array of eleven values evenly spaced between 0 and 1
np.linspace(0, 1, 11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [19]:
# Create a 3x3 array of uniformly distributed
# random values between 0 and 1
np.random.random((3, 3))

array([[0.81839744, 0.16073876, 0.146925  ],
       [0.89842456, 0.58238505, 0.09486272],
       [0.12868698, 0.95899586, 0.08063801]])

In [20]:
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
np.random.normal(0, 1, (3, 3))

array([[ 2.08076691,  0.14016855, -0.16606138],
       [-0.12792012,  1.69532352, -0.7313267 ],
       [-0.85035347,  0.49944241, -0.39537594]])

In [21]:
# Create a 3x3 array of random integers in the interval [0, 10)
np.random.randint(0, 10, (3, 3))

array([[4, 2, 1],
       [9, 7, 9],
       [0, 8, 2]])

In [22]:
# Create a 10x10 array of random integers in the interval [1, 7)
np.random.randint(1, 7, (10, 10))

array([[2, 4, 4, 6, 4, 1, 1, 4, 1, 3],
       [6, 1, 3, 5, 1, 5, 2, 6, 1, 6],
       [1, 4, 2, 6, 3, 2, 6, 4, 1, 6],
       [3, 2, 5, 4, 2, 5, 5, 5, 2, 6],
       [3, 6, 4, 5, 2, 6, 6, 3, 4, 1],
       [2, 1, 1, 5, 5, 4, 3, 2, 4, 3],
       [1, 1, 2, 2, 6, 2, 4, 4, 5, 6],
       [3, 1, 6, 2, 3, 2, 1, 1, 2, 1],
       [1, 4, 1, 6, 3, 6, 5, 6, 5, 3],
       [5, 6, 3, 5, 5, 4, 4, 4, 1, 6]])

In [23]:
# Create an uninitialized array of three integers
# The values will be whatever happens to already exist at that memory location
np.empty(3)

array([7.9140206e-312, 0.0000000e+000, 6.4759160e-319])

# NumPy Standard Data Types

In [24]:
# When constructing an array, they can be specified using a string
np.zeros(10, dtype='int16')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [25]:
# Or using the associated NumPy object
np.zeros(10, dtype=np.int16)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

|Data type	|Description|
|:----------|:----------|
|bool_	    |Boolean (True or False) stored as a byte
|int_	    |Default integer type (same as C long; normally either int64 or int32)
|intc	    |Identical to C int (normally int32 or int64)
|intp	    |Integer used for indexing (same as C ssize_t; normally either int32 or int64)
|int8	    |Byte (-128 to 127)
|int16	    |Integer (-32768 to 32767)
|int32	    |Integer (-2147483648 to 2147483647)
|int64	    |Integer (-9223372036854775808 to 9223372036854775807)
|uint8	    |Unsigned integer (0 to 255)
|uint16	    |Unsigned integer (0 to 65535)
|uint32	    |Unsigned integer (0 to 4294967295)
|uint64	    |Unsigned integer (0 to 18446744073709551615)
|float_	    |Shorthand for float64.
|float16 	|Half precision float: sign bit, 5 bits exponent, 10 bits mantissa
|float32 	|Single precision float: sign bit, 8 bits exponent, 23 bits mantissa
|float64	|Double precision float: sign bit, 11 bits exponent, 52 bits mantissa
|complex_	|Shorthand for complex128.
|complex64	|Complex number, represented by two 32-bit floats
|complex128	|Complex number, represented by two 64-bit floats